### ISSUE TITLE
Reading and saving temperature / humidity

### ISSUE THREAD

**Issue by shusuke0812** [shusuke0812/Kikurage-Device#12]
## TODO
- [ ] reading temperature / humidity by using DHT11
- [ ] saving temperature / humidity to Firestore
- [ ] changing display by temperature / humidity

## Ref
- https://karakuri-musha.com/inside-technology/arduino-m5stickc-07-temp-and-humidity-sensor/
